const dummyDataArray = [
  {
    firstName: "John",
    lastName: "Doe",
    email: "johndoe@example.com",
    phoneNumber: "+1234567890",
    company: "Tech Innovators Inc.",
    jobTitle: "Software Engineer",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    email: "janesmith@example.com",
    phoneNumber: "+1987654321",
    company: "Creative Solutions Ltd.",
    jobTitle: "Product Manager",
  },
  {
    firstName: "Sam",
    lastName: "Wilson",
    email: "samwilson@example.com",
    phoneNumber: "+1122334455",
    company: "Global Tech Corp.",
    jobTitle: "Data Scientist",
  },
  {
    firstName: "Emily",
    lastName: "Davis",
    email: "emilydavis@example.com",
    phoneNumber: "+5544332211",
    company: "Digital Ventures",
    jobTitle: "UX/UI Designer",
  },
  {
    firstName: "Michael",
    lastName: "Brown",
    email: "michaelbrown@example.com",
    phoneNumber: "+6655443322",
    company: "Innovative Solutions",
    jobTitle: "Software Architect",
  },
  {
    firstName: "Olivia",
    lastName: "Johnson",
    email: "oliviajohnson@example.com",
    phoneNumber: "+9988776655",
    company: "SmartTech Solutions",
    jobTitle: "Systems Analyst",
  },
  {
    firstName: "Liam",
    lastName: "Martinez",
    email: "liammartinez@example.com",
    phoneNumber: "+1230984567",
    company: "FutureTech Inc.",
    jobTitle: "DevOps Engineer",
  },
  {
    firstName: "Sophia",
    lastName: "Garcia",
    email: "sophiagarcia@example.com",
    phoneNumber: "+5678901234",
    company: "TechGiant Enterprises",
    jobTitle: "Business Analyst",
  },
  {
    firstName: "Ethan",
    lastName: "Moore",
    email: "ethanmoore@example.com",
    phoneNumber: "+1011121314",
    company: "NextGen Systems",
    jobTitle: "Cloud Engineer",
  },
  {
    firstName: "Ava",
    lastName: "Taylor",
    email: "avataylor@example.com",
    phoneNumber: "+9876543210",
    company: "Creative Minds Co.",
    jobTitle: "Content Strategist",
  },
  {
    firstName: "Mason",
    lastName: "Anderson",
    email: "masonanderson@example.com",
    phoneNumber: "+1928374650",
    company: "Tech Innovators Inc.",
    jobTitle: "Front-End Developer",
  },
  {
    firstName: "Isabella",
    lastName: "Thomas",
    email: "isabellathomas@example.com",
    phoneNumber: "+3322114455",
    company: "Global Innovations",
    jobTitle: "Marketing Manager",
  },
  {
    firstName: "Lucas",
    lastName: "Hernandez",
    email: "lucashernandez@example.com",
    phoneNumber: "+5566778899",
    company: "DataWorks Ltd.",
    jobTitle: "Data Engineer",
  },
  {
    firstName: "Charlotte",
    lastName: "King",
    email: "charlotteking@example.com",
    phoneNumber: "+4433221100",
    company: "Innovative Solutions",
    jobTitle: "QA Engineer",
  },
  {
    firstName: "Benjamin",
    lastName: "White",
    email: "benjaminwhite@example.com",
    phoneNumber: "+7788992233",
    company: "Tech Innovators Inc.",
    jobTitle: "Mobile App Developer",
  },
  {
    firstName: "Amelia",
    lastName: "Scott",
    email: "ameliascott@example.com",
    phoneNumber: "+5566771122",
    company: "NextGen Innovations",
    jobTitle: "Business Development Manager",
  },
  {
    firstName: "James",
    lastName: "Wright",
    email: "jameswright@example.com",
    phoneNumber: "+9988772233",
    company: "Digital Innovations",
    jobTitle: "SEO Specialist",
  },
];

export default dummyDataArray;
